# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      is_key_content_base64: true,
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    increment_build_number(xcodeproj: "SoundRecorder.xcodeproj")
    setup_ci

    sync_code_signing(  
      type: "appstore",
      readonly: is_ci
    )
    match(type: "appstore", git_basic_authorization: ENV["MATCH_PERSONAL_ACCESS_TOKEN"], api_key: api_key)
    build_app(scheme: "SoundRecorder", export_method: "app-store", export_options: { provisioningProfiles:{ "com.gingermcninja.SoundRecorder": "match AppStore com.gingermcninja.SoundRecorder"}})
    upload_to_testflight()
  end
end
