# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "4Y72995Z84",
      issuer_id: "4fdc9f6b-6607-43d5-a3be-940cc2d82183",
      key_filepath: "./AuthKey_4Y72995Z84.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    increment_build_number(xcodeproj: "SoundRecorder.xcodeproj")
    build_app(scheme: "SoundRecorder", export_method: "app-store", export_options: { provisioningProfiles:{ "com.gingermcninja.SoundRecorder": "match AppStore com.gingermcninja.SoundRecorder"}})
    upload_to_testflight(api_key: api_key)
  end
end
